### ISSUE TITLE
omitted width/height in favor of viewbox causes resizing problems

### ISSUE THREAD

**Issue by calvinfo** [logo/cli#6]
We just received an svg from swiftly which ommitted the `width` and `height` fields:

https://github.com/logo/calq/blob/1.0.2/images/logo.svg

We're not sure whether this is a new illustrator problem, or a one-off problem with the way the designer implemented since it says generated with illustrator `17.1.0`.

@ianstormtaylor 

cc @amillet89

**Comment by ianstormtaylor** [comment]
Hmm honestly not sure, but we've got creds for adobe illustrator so that
you guys can have a copy

On Wed, Oct 8, 2014 at 5:06 PM, Calvin French-Owen <notifications@github.com

**Comment by amillet89** [comment]
tiny simplifi logo provides more support to the illustrator 17.1.0 theory:
https://raw.githubusercontent.com/logo/simplifi/master/images/logo.svg
looks like height and width params are no longer in the svg head tag, but encapsulated in the "viewBox" attribute.
